language: php
php:
  - 5.4
  - 5.5
  - 5.6
addons:
  code_climate:
    repo_token: 97556cc0507864cd70cb0d710a278a9e5748292c38b8b080e730756e3fa458f0
before_script: composer install
script: phpunit --coverage-clover build/logs/clover.xml --bootstrap vendor/autoload.php tests
after_script:
  - vendor/bin/test-reporter

