language: php
php:
  - 5.6
  - 7.0
addons:
  code_climate:
    repo_token: e9193b107e8df98973444d74d5b16b2f7e6605b03542c4a4844153281d81c660
before_script:
  - sed -i '/phpdoc/d' composer.json
  - composer install
script:
  - ./vendor/bin/phpunit --configuration test/phpunit.xml test
  - ./vendor/bin/phpcs --ignore=*/vendor/*,*/bin/*,*/*.min.js --standard=PSR2 .
  - ./vendor/bin/phpcs --standard=./vendor/athens/standard/ruleset.xml src
after_script:
  - vendor/bin/test-reporter